language: "en-US"
early_access: true
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "wip"
      - "draft"
  tools:
    ast-grep:
      enabled: true
    ruff:
      enabled: true
chat:
  auto_reply: true
